# Generated by Django 4.0.3 on 2022-10-23 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=10)),
                ('add', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('edu', models.CharField(max_length=50)),
                ('det', models.CharField(max_length=50)),
                ('image', models.ImageField(default='default.svg', upload_to='pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentP',
        ),
    ]
