# Generated by Django 4.0.3 on 2022-10-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('add', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('edu', models.CharField(max_length=20)),
                ('det', models.CharField(max_length=20)),
                ('image', models.ImageField(default='default.svg', upload_to='pics')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentP',
        ),
    ]
