# Generated by Django 4.0.3 on 2022-10-23 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_profile_delete_studentp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
